export type ProjectType = "game" | "library" | "app" | "finance" | "tool"
export type ProjectStatus = "live" | "demo" | "wip"

export interface Project {
  slug: string
  name: string
  /** Short, card-length blurb. */
  description: string
  /** One line shown under the title on the project detail page (falls back to description). */
  tagline?: string
  /** 2–3 sentence "what & why" for the detail page (falls back to description). */
  overview?: string
  /** Punchy feature/decision bullets for the detail page. */
  highlights?: string[]
  type: ProjectType
  status: ProjectStatus
  year: number
  tags: string[]
  liveUrl?: string
  sourceUrl?: string
  /** A dedicated write-up / about page on the project's own site, if one exists. */
  aboutUrl?: string
  /**
   * Detail-page imagery. Both default by convention to
   * `/projects/<slug>/cover.svg` and `/projects/<slug>/01.svg`, `02.svg`,
   * so dropping real screenshots in that folder is all it takes. Set these
   * only to point somewhere else. A project with no imagery at all falls back
   * to the typographic cover in <ProjectCover>.
   */
  cover?: string
  /** Image shown on the project card. Falls back to `cover`. */
  cardImage?: string
  screenshots?: string[]
  /**
   * Aspect treatment for the cover + gallery imagery. Defaults to "landscape"
   * (16/10, cropped to fill). Use "portrait" for tall phone screenshots so they
   * render contained instead of being cropped to a sliver.
   */
  imageOrientation?: "landscape" | "portrait"
  featured: boolean
  /** Surface this project in the recruiter "Selected projects" grid. */
  recruiterHighlight?: boolean
  /** A deeper technical note shown on /engineers. */
  engineerNote?: string
}

export const STATUS_LABELS: Record<ProjectStatus, string> = {
  live: "Live",
  demo: "Demo",
  wip: "In progress",
}

export const TYPE_LABELS: Record<ProjectType, string> = {
  game: "Game",
  library: "Library",
  app: "App",
  finance: "Finance",
  tool: "Tooling",
}

/**
 * Ordered most-interesting-first: the home page shows the leading slice
 * (see HOME_PROJECT_COUNT), /work shows all of them.
 */
export const projects: Project[] = [
  {
    slug: "idle-dungeon-life",
    name: "Idle Dungeon Life",
    description:
      "An idle RPG where your adventurer ages in real time and dives ever-deeper dungeons until their lifespan runs out — death carries “legacy ash” into the next life.",
    tagline: "Every character lives once.",
    overview:
      "An idle RPG where you send an adventurer into ancient dungeons; they age in real time, gather traits, and push deeper until their lifespan runs out. Death isn't a setback, it's progress — “legacy ash” carries across lives to fund permanent unlocks. The whole game runs on a pure, event-sourced reducer kept entirely separate from the Phaser presentation layer, so the same logic powers the game, an offline catch-up, a headless balance simulator, and the test suite.",
    highlights: [
      "Lifespan-as-health: a run is one lifetime — the character ages through life stages and dies when vitality is spent, not from HP loss.",
      "16 dungeons from the Abandoned Chapel down to The Wound, each deadlier than the last.",
      "Three legacy paths — Holy, Abyss, and Knowledge — each with its own talent tree and multi-life perk line.",
      "Traits surface and evolve as the character ages or alignment shifts; sub-characters unlock parallel lives after the final dungeon.",
      "Offline progression with a welcome-back summary, plus a “Watch demo” button that auto-plays a full lifetime in a sandbox that never touches your save.",
      "Pure, event-sourced reducer holds all game logic, fully decoupled from the Phaser presentation layer.",
      "Deterministic seeded RNG — same seed + same events ⇒ same outcome — powering trustworthy offline catch-up and a headless balance simulator that runs the real logic across many seeds and strategies.",
      "Versioned save format with field-by-field migration; 170+ Vitest unit tests and a Playwright e2e suite, with screenshots generated by Playwright driving the real game.",
    ],
    type: "game",
    status: "live",
    year: 2026,
    tags: ["TypeScript", "Phaser 3", "Vite", "Capacitor", "Vitest", "Playwright", "Vercel"],
    liveUrl: "https://dungeonlife.nikolayvalev.com/",
    sourceUrl: "https://github.com/NikolayValev/IdleDungeonLife",
    cover: "/projects/idle-dungeon-life/02-early-chapel.png",
    cardImage: "/projects/idle-dungeon-life/card.png",
    screenshots: [
      "/projects/idle-dungeon-life/01-intro.png",
      "/projects/idle-dungeon-life/02-early-chapel.png",
      "/projects/idle-dungeon-life/03-mid-dungeon.png",
      "/projects/idle-dungeon-life/04-deep-dungeon.png",
      "/projects/idle-dungeon-life/05-talents.png",
      "/projects/idle-dungeon-life/06-codex.png",
      "/projects/idle-dungeon-life/07-subs.png",
      "/projects/idle-dungeon-life/08-death-legacy.png",
    ],
    imageOrientation: "portrait",
    featured: true,
    recruiterHighlight: true,
    engineerNote:
      "All game logic lives in a single pure, event-sourced reducer kept entirely separate from the Phaser presentation layer, so it runs headless in Node. Deterministic seeded RNG (same seed + same events ⇒ same outcome) powers trustworthy offline catch-up and a headless balance simulator that exercises the real game across many seeds and strategies; a versioned save format migrates field-by-field so existing players never lose progress. Tested with 170+ Vitest unit tests plus a Playwright e2e suite that also drives the real game to generate screenshots.",
  },
  {
    slug: "design-system",
    name: "Design System",
    description:
      "A token-driven React component library: 12 OKLCH themes with hand-tuned light and dark palettes, shipped to npm alongside a hosted MCP server that lets AI agents install components.",
    tagline: "One component set, twelve themes, and an MCP server so agents can install it themselves.",
    overview:
      "A component library where nothing hardcodes color, type, or spacing — every component reads semantic CSS custom properties, so an entire visual theme is a swap of variables rather than a rewrite. Twelve curated “visions” across five families each ship a native light and dark palette, and a hosted Model Context Protocol server exposes the catalog so agents like Claude or Cursor can browse and install components directly. This site runs on it.",
    highlights: [
      "Tokens in OKLCH, a perceptually-uniform color space — semantic --vde-* variables with shadcn-compatible aliases.",
      "12 curated visions across 5 families, each with a hand-tuned light and dark palette, switchable at runtime.",
      "A hosted MCP server so Claude, Cursor, and Windsurf can browse, fetch, and install components without a human copying files.",
      "Components read entirely from CSS variables, so identical markup re-skins instantly across visions.",
      "TurboRepo + pnpm monorepo with Storybook visual-regression tests, semantic-versioned npm releases, and Terraform IaC.",
      "Powers this very site, including the warm terracotta theme you're viewing.",
    ],
    type: "library",
    status: "live",
    year: 2026,
    tags: ["TypeScript", "React", "Tailwind", "Storybook", "TurboRepo", "MCP"],
    liveUrl: "https://designsystem.nikolayvalev.com/",
    sourceUrl: "https://github.com/NikolayValev/design-system",
    cover: "/projects/design-system/card.png",
    screenshots: [],
    featured: true,
    recruiterHighlight: true,
    engineerNote:
      "A token-driven component library: components never hardcode colors, they read semantic CSS custom properties defined in OKLCH, so a whole theme is a swap of variables — twelve of them ship, each with a hand-tuned light and dark palette. Distribution is the interesting half: alongside the npm package, a hosted MCP server exposes the component catalog so coding agents can install components without a human copying files. This very site is built on it.",
  },
  {
    slug: "ralph",
    name: "Ralph",
    description:
      "An autonomous agent that picks up its own Linear tickets, ships one increment per run, and opens a pull request it is never allowed to merge.",
    tagline: "An autonomous ticket agent, built brakes-first.",
    overview:
      "Ralph watches a Linear backlog for tickets labelled autonomous-eligible, wakes on a schedule, does exactly one increment of work, opens a pull request, and stops — leaving the PR in review for a human. The interesting engineering isn't the agent loop; it's everything constraining it: a preflight that refuses to run under the wrong credentials, a circuit breaker that halts the schedule after repeated failures, and a hard rule that it never merges and never deploys.",
    highlights: [
      "One increment per run: wake, pick a ticket, make a bounded change, open a PR, stop.",
      "Never merges and never deploys — every run ends in review, on a branch, behind a human.",
      "A circuit breaker trips the schedule after repeated failures instead of looping on a broken repo.",
      "Preflight refuses to start under the wrong credentials, or with a test command that turns out to be a watcher — verified empirically rather than assumed.",
      "Two-tier model routing: a local Ollama model triages cheaply before anything expensive runs.",
      "Reports each tick to Slack, with inbound Socket Mode handlers for talking back to it.",
      "Runs natively on Windows under Task Scheduler and Git Bash — no WSL, no second toolchain.",
    ],
    type: "tool",
    status: "wip",
    year: 2026,
    tags: ["Python", "Claude Code", "Linear", "Slack", "Ollama", "GitHub"],
    sourceUrl: "https://github.com/NikolayValev/Agentic-Ralph-runner",
    screenshots: [],
    featured: true,
    recruiterHighlight: true,
    engineerNote:
      "An agent that writes code unsupervised is mostly a guardrail problem, so the design is brakes-first: one increment per run, a PR that is always left in review, and a hard prohibition on merging or deploying. A preflight verifies the environment empirically — credentials, tool flags, and a test command that must not be a watcher — and refuses to start rather than failing halfway; a circuit breaker stops the schedule after repeated failures instead of hammering a broken repo. Model spend is tiered, with a local Ollama model triaging before anything expensive runs.",
  },
  {
    slug: "bondviz",
    name: "Bond Visualizer",
    description:
      "Live U.S. Treasury data to visualize the yield curve and price bonds — present value, duration, convexity, and parallel-shift scenarios, with hand-rolled D3 charts.",
    tagline: "A fixed-income research terminal: live Treasury data, the yield curve, and bond math from scratch.",
    overview:
      "Pulls live U.S. Treasury data to visualize the yield curve and price bonds — present value, duration, convexity, and parallel-shift scenarios — with hand-rolled D3 charts. A fixed-income and markets research terminal built on continuous-compounding analytics.",
    highlights: [
      "Live U.S. Treasury data drives the yield curve in real time.",
      "Bond pricing with present value, duration, convexity, and parallel-shift scenarios.",
      "Portfolio view plus PCA on the curve's principal movements.",
      "Hand-rolled D3 charts — no charting library.",
    ],
    type: "finance",
    status: "live",
    year: 2026,
    tags: ["TypeScript", "React", "Tailwind", "Python", "Pandas", "D3", "C++"],
    liveUrl: "https://bondviz.nikolayvalev.com/",
    sourceUrl: "https://github.com/NikolayValev/bondviz",
    cover: "/projects/bondviz/card.png",
    screenshots: [],
    featured: true,
    recruiterHighlight: true,
    engineerNote:
      "Bond math is hand-rolled on continuous-compounding analytics — present value, duration, convexity, and parallel-shift scenarios over live Treasury data — and every chart is drawn directly with D3 rather than a charting library, so the visualization stays exactly as expressive as the model.",
  },
  {
    slug: "quitting-smoking-tracker",
    name: "Quitting Smoking Tracker",
    description:
      "A smoke-free companion: track your streak, hit health and savings milestones, and get through cravings — with a public demo that needs no sign-in.",
    tagline: "A smoke-free companion: track streaks, hit milestones, and get through cravings.",
    overview:
      "A tracker for quitting smoking — log your streak, celebrate milestones, and watch health and money recovered add up over time. Guided breathing exercises and urge-resistance steps help get you through cravings. It runs in two modes from one codebase: a read-only public demo seeded with 90 days of realistic data, and an authenticated mode where your own logs live in Postgres.",
    highlights: [
      "A public demo at /demo — the full UI on seeded data, no account required.",
      "Authenticated mode with per-user logs in Neon Postgres, isolated row by row.",
      "Streak tracking with health and savings milestones over time.",
      "Guided breathing exercises and step-by-step urge-resistance coping strategies.",
      "Personalized onboarding, daily wellness tips, and milestone celebrations.",
    ],
    type: "app",
    status: "live",
    year: 2026,
    tags: ["Next.js", "TypeScript", "Drizzle", "Neon Postgres", "Clerk", "Playwright"],
    liveUrl: "https://smoking.nikolayvalev.com/",
    sourceUrl: "https://github.com/NikolayValev/quitting-smoking-tracker",
    cover: "/projects/quitting-smoking-tracker/card.png",
    screenshots: [],
    featured: true,
    recruiterHighlight: true,
    engineerNote:
      "One codebase serves two modes: a read-only public demo rendered from a seeded fixture so anyone can explore the full UI without an account, and an authenticated mode where logs are user-scoped rows in Neon Postgres behind Clerk. Keeping the demo a real render of the same components — rather than a screenshot tour — means the shared path stays honest, and the data layer is the only thing that swaps.",
  },
  {
    slug: "secondbrain",
    name: "Second Brain",
    description:
      "An AI-powered personal knowledge base over an Obsidian vault — capture notes, search semantically, and ask questions answered from your own writing.",
    tagline: "An AI-powered personal knowledge base — capture, search, and ask your own notes.",
    overview:
      "A personal knowledge-management system powered by AI: capture notes to an inbox, search across everything, and ask questions that are answered from your own notes via retrieval-augmented generation over an Obsidian vault. A FastAPI service handles indexing and retrieval; the Next.js frontend is generated against its OpenAPI contract.",
    highlights: [
      "Ask your notes: a RAG pipeline answers questions from your own knowledge base.",
      "Semantic search over an Obsidian vault, with embeddings stored in Postgres via pgvector.",
      "Provider-agnostic by design — OpenAI, Anthropic, and Google models sit behind one interface.",
      "Inbox-to-knowledge capture flow with a unified dashboard.",
      "A typed frontend client generated from the backend's OpenAPI schema, so contract drift breaks CI instead of production.",
    ],
    type: "app",
    status: "live",
    year: 2026,
    tags: ["Next.js", "FastAPI", "pgvector", "RAG", "Obsidian", "OpenAPI"],
    liveUrl: "https://secondbrain.nikolayvalev.com/",
    sourceUrl: "https://github.com/NikolayValev/second-brain-ui",
    cover: "/projects/secondbrain/card.png",
    screenshots: [],
    featured: true,
    recruiterHighlight: true,
    engineerNote:
      "A FastAPI indexing and retrieval service with embeddings in Postgres via pgvector, fronted by a Next.js app whose API client is generated from the backend's OpenAPI schema — so a contract change breaks the build rather than a user's request. LLM providers sit behind a single interface, which is what makes swapping between OpenAI, Anthropic, and Google models a config change instead of a rewrite.",
  },
  {
    slug: "mandate-zero",
    name: "Mandate Zero",
    description:
      "Deterministic turn-based crisis simulation with seeded runs, multilingual support, and optional authentication.",
    tagline: "A deterministic, turn-based crisis simulation — same seed, same run, every time.",
    overview:
      "A turn-based strategy simulation where you steer an escalating crisis. It's fully deterministic: the same seed always reproduces the same run, which keeps the simulation reproducible and testable. Multilingual support and optional auth sit on top without compromising that determinism.",
    highlights: [
      "Deterministic core: an identical seed always produces an identical run.",
      "Reproducible, replayable, and testable by construction.",
      "Multilingual support layered on without breaking determinism.",
      "Optional authentication for saved runs.",
    ],
    type: "game",
    status: "live",
    year: 2026,
    tags: ["Next.js", "TypeScript", "Supabase", "Tailwind"],
    liveUrl: "https://mandate-zero.nikolayvalev.com/",
    sourceUrl: "https://github.com/NikolayValev/mandate-zero",
    cover: "/projects/mandate-zero/card.png",
    screenshots: [],
    featured: true,
    recruiterHighlight: true,
    engineerNote:
      "Fully deterministic: the same seed always produces the same run, which makes the simulation reproducible and testable. Adds multilingual support and optional auth on top without compromising that determinism.",
  },
]

export const featuredProjects = projects.filter((p) => p.featured)

/** How many featured projects the home page shows before "View all". */
export const HOME_PROJECT_COUNT = 6

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug)
}
