export type ProjectType = "game" | "library" | "app" | "finance"
export type ProjectStatus = "live" | "demo" | "wip"

export interface Project {
  slug: string
  name: string
  /** Short, card-length blurb. */
  description: string
  /** One line shown under the title on the project detail page (falls back to description). */
  tagline?: string
  /** 2–3 sentence "what & why" for the detail page (falls back to description). */
  overview?: string
  /** Punchy feature/decision bullets for the detail page. */
  highlights?: string[]
  type: ProjectType
  status: ProjectStatus
  year: number
  tags: string[]
  liveUrl?: string
  sourceUrl?: string
  /** A dedicated write-up / about page on the project's own site, if one exists. */
  aboutUrl?: string
  /**
   * Detail-page imagery. Both default by convention to
   * `/projects/<slug>/cover.svg` and `/projects/<slug>/01.svg`, `02.svg`,
   * so dropping real screenshots in that folder is all it takes. Set these
   * only to point somewhere else.
   */
  cover?: string
  screenshots?: string[]
  /**
   * Aspect treatment for the cover + gallery imagery. Defaults to "landscape"
   * (16/10, cropped to fill). Use "portrait" for tall phone screenshots so they
   * render contained instead of being cropped to a sliver.
   */
  imageOrientation?: "landscape" | "portrait"
  featured: boolean
  /** Surface this project in the recruiter "Selected projects" grid. */
  recruiterHighlight?: boolean
  /** A deeper technical note shown on /engineers. */
  engineerNote?: string
}

export const projects: Project[] = [
  {
    slug: "design-system",
    name: "Design System",
    description:
      "Token-driven React component library with intent-based recipes, multiple visual themes, and Tailwind CSS presets.",
    tagline: "A token-driven React component library that re-themes by swapping CSS variables.",
    overview:
      "A component library where nothing hardcodes color, type, or spacing — every component reads CSS custom properties, so an entire visual theme is a swap of variables rather than a rewrite. This site runs on it.",
    highlights: [
      "Intent-based recipes: components say what they are; tokens decide how they look.",
      "Multiple visual themes from one component set — swap variables, not components.",
      "Ships Tailwind CSS presets so the tokens drop into any project.",
      "Powers this very site, including the warm terracotta theme you're viewing.",
    ],
    type: "library",
    status: "live",
    year: 2026,
    tags: ["TypeScript", "React", "Tailwind", "Storybook"],
    liveUrl: "https://designsystem.nikolayvalev.com/",
    featured: true,
    engineerNote:
      "A token-driven component library: components never hardcode colors, they read CSS custom properties, so a whole theme is a swap of variables. This very site is built on it.",
  },
  {
    slug: "idle-dungeon-life",
    name: "Idle Dungeon Life",
    description:
      "An idle RPG where your adventurer ages in real time and dives ever-deeper dungeons until their lifespan runs out — death carries “legacy ash” into the next life.",
    tagline: "Every character lives once.",
    overview:
      "An idle RPG where you send an adventurer into ancient dungeons; they age in real time, gather traits, and push deeper until their lifespan runs out. Death isn't a setback, it's progress — “legacy ash” carries across lives to fund permanent unlocks. The whole game runs on a pure, event-sourced reducer kept entirely separate from the Phaser presentation layer, so the same logic powers the game, an offline catch-up, a headless balance simulator, and the test suite.",
    highlights: [
      "Lifespan-as-health: a run is one lifetime — the character ages through life stages and dies when vitality is spent, not from HP loss.",
      "16 dungeons from the Abandoned Chapel down to The Wound, each deadlier than the last.",
      "Three legacy paths — Holy, Abyss, and Knowledge — each with its own talent tree and multi-life perk line.",
      "Traits surface and evolve as the character ages or alignment shifts; sub-characters unlock parallel lives after the final dungeon.",
      "Offline progression with a welcome-back summary, plus a “Watch demo” button that auto-plays a full lifetime in a sandbox that never touches your save.",
      "Pure, event-sourced reducer holds all game logic, fully decoupled from the Phaser presentation layer.",
      "Deterministic seeded RNG — same seed + same events ⇒ same outcome — powering trustworthy offline catch-up and a headless balance simulator that runs the real logic across many seeds and strategies.",
      "Versioned save format with field-by-field migration; 171 Vitest unit tests + a Playwright e2e suite, with screenshots generated by Playwright driving the real game.",
    ],
    type: "game",
    status: "live",
    year: 2026,
    tags: ["TypeScript", "Phaser 3", "Vite", "Capacitor", "Vitest", "Playwright", "Vercel"],
    liveUrl: "https://dungeonlife.nikolayvalev.com/",
    sourceUrl: "https://github.com/NikolayValev/IdleDungeonLife",
    cover: "/projects/idle-dungeon-life/01-intro.png",
    screenshots: [
      "/projects/idle-dungeon-life/01-intro.png",
      "/projects/idle-dungeon-life/02-early-chapel.png",
      "/projects/idle-dungeon-life/03-mid-dungeon.png",
      "/projects/idle-dungeon-life/04-deep-dungeon.png",
      "/projects/idle-dungeon-life/05-talents.png",
      "/projects/idle-dungeon-life/06-codex.png",
      "/projects/idle-dungeon-life/07-subs.png",
      "/projects/idle-dungeon-life/08-death-legacy.png",
    ],
    imageOrientation: "portrait",
    featured: true,
    recruiterHighlight: true,
    engineerNote:
      "All game logic lives in a single pure, event-sourced reducer kept entirely separate from the Phaser presentation layer, so it runs headless in Node. Deterministic seeded RNG (same seed + same events ⇒ same outcome) powers trustworthy offline catch-up and a headless balance simulator that exercises the real game across many seeds and strategies; a versioned save format migrates field-by-field so existing players never lose progress. Tested with 171 Vitest unit tests plus a Playwright e2e suite that also drives the real game to generate screenshots.",
  },
  {
    slug: "mandate-zero",
    name: "Mandate Zero",
    description:
      "Deterministic turn-based crisis simulation with seeded runs, multilingual support, and optional authentication.",
    tagline: "A deterministic, turn-based crisis simulation — same seed, same run, every time.",
    overview:
      "A turn-based strategy simulation where you steer an escalating crisis. It's fully deterministic: the same seed always reproduces the same run, which keeps the simulation reproducible and testable. Multilingual support and optional auth sit on top without compromising that determinism.",
    highlights: [
      "Deterministic core: an identical seed always produces an identical run.",
      "Reproducible, replayable, and testable by construction.",
      "Multilingual support layered on without breaking determinism.",
      "Optional authentication for saved runs.",
    ],
    type: "game",
    status: "live",
    year: 2026,
    tags: ["Next.js", "TypeScript", "Supabase", "Tailwind"],
    liveUrl: "https://mandate-zero.nikolayvalev.com/",
    sourceUrl: "https://github.com/NikolayValev/mandate-zero",
    featured: true,
    recruiterHighlight: true,
    engineerNote:
      "Fully deterministic: the same seed always produces the same run, which makes the simulation reproducible and testable. Adds multilingual support and optional auth on top without compromising that determinism.",
  },
  {
    slug: "bondviz",
    name: "Bond Visualizer",
    description:
      "Live U.S. Treasury data to visualize the yield curve and price bonds — present value, duration, convexity, and parallel-shift scenarios, with hand-rolled D3 charts.",
    tagline: "A fixed-income research terminal: live Treasury data, the yield curve, and bond math from scratch.",
    overview:
      "Pulls live U.S. Treasury data to visualize the yield curve and price bonds — present value, duration, convexity, and parallel-shift scenarios — with hand-rolled D3 charts. A fixed-income and markets research terminal built on continuous-compounding analytics.",
    highlights: [
      "Live U.S. Treasury data drives the yield curve in real time.",
      "Bond pricing with present value, duration, convexity, and parallel-shift scenarios.",
      "Portfolio view plus PCA on the curve's principal movements.",
      "Hand-rolled D3 charts — no charting library.",
    ],
    type: "finance",
    status: "live",
    year: 2026,
    tags: ["TypeScript", "React", "Tailwind", "Python", "Pandas", "D3", "C++"],
    liveUrl: "https://bondviz.nikolayvalev.com/",
    sourceUrl: "https://github.com/NikolayValev/bondviz",
    featured: true,
    recruiterHighlight: true,
    engineerNote:
      "Bond math is hand-rolled on continuous-compounding analytics — present value, duration, convexity, and parallel-shift scenarios over live Treasury data — and every chart is drawn directly with D3 rather than a charting library, so the visualization stays exactly as expressive as the model.",
  },
  {
    slug: "secondbrain",
    name: "Second Brain",
    description:
      "An AI-powered personal knowledge base — capture notes, search everything, and ask questions answered from your own notes.",
    tagline: "An AI-powered personal knowledge base — capture, search, and ask your own notes.",
    overview:
      "A personal knowledge-management system powered by AI: capture notes to an inbox, search across everything, and ask questions that are answered from your own notes via retrieval-augmented generation over an Obsidian vault.",
    highlights: [
      "Ask your notes: a RAG pipeline answers questions from your own knowledge base.",
      "Full-text search over an Obsidian vault, backed by Elasticsearch.",
      "Inbox-to-knowledge capture flow with a unified dashboard.",
      "Authenticated and multi-device, with web and mobile layouts.",
    ],
    type: "app",
    status: "live",
    year: 2026,
    tags: ["Next.js", "RAG", "Obsidian", "Elasticsearch", "LLM"],
    liveUrl: "https://secondbrain.nikolayvalev.com/",
    sourceUrl: "https://github.com/NikolayValev/second-brain-ui",
    featured: true,
    recruiterHighlight: true,
  },
  {
    slug: "quitting-smoking-tracker",
    name: "Quitting Smoking Tracker",
    description:
      "A smoke-free companion: track your streak, hit health and savings milestones, and get through cravings.",
    tagline: "A smoke-free companion: track streaks, hit milestones, and get through cravings.",
    overview:
      "A tracker for quitting smoking — log your streak, celebrate milestones, and watch health and money recovered add up over time. Guided breathing exercises and wellness tips help get you through cravings.",
    highlights: [
      "Streak tracking with health and savings milestones over time.",
      "Guided breathing exercises for craving moments.",
      "Wellness tips and personalized encouragement.",
      "Accounts and sync so progress follows you across devices.",
    ],
    type: "app",
    status: "live",
    year: 2025,
    tags: ["Next.js", "TypeScript", "Tailwind", "Clerk"],
    liveUrl: "https://smoking.nikolayvalev.com/",
    sourceUrl: "https://github.com/NikolayValev/quitting-smoking-tracker",
    featured: true,
    recruiterHighlight: true,
  },
]

export const featuredProjects = projects.filter((p) => p.featured)

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug)
}
